apiVersion: v1
kind: Pod
metadata:
  name: conversor-temperatura
  labels:
   cor: azul   
spec:
  containers: 
  - name: conversor-temperatura
    image: rlsilva/conversao-temperatura:latest
    ports: 
    - containerPort: 80